version: "3.9"

services:
  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      MONGO_URI: "${MONGO_URI}"
      PYTHONPATH: "/opt/airflow/scripts"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./.env:/opt/airflow/.env
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    # ✅ On ne met plus de commande custom ici
