services:

  mongo:
    image: mongo:7
    container_name: ecotraffic-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: ecotraffic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecotraffic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./airflow/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: ecotraffic-airflow
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_db
      AIRFLOW__SCHEDULER__HEARTBEAT_SEC: "10"
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "30"
      AIRFLOW__CORE__PARALLELISM: "4"
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "4"
      MONGODB_URI: mongodb://mongo:27017
      MONGO_DB: ecotraffic
      MONGO_COLLECTION: traffic
      MONGO_URI: mongodb://mongo:27017/ecotraffic
      MONGO_COLLECTION_ENV: weather_pollution
      WEATHER_API_URL: https://api.open-meteo.com/v1/forecast
      AIR_QUALITY_API_URL: https://air-quality-api.open-meteo.com/v1/air-quality
      LATITUDE: "48.1173"
      LONGITUDE: "-1.6778"
      POSTGRES_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/ecotraffic
      POSTGRES_TABLE_ENV: environment_features
      PYTHONPATH: /opt/ecotraffic:/opt/ecotraffic/ecotraffic/src:/opt/airflow:/opt/airflow/kedro_preprocessing/src
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins
      - ./:/opt/ecotraffic
      - ./kedro_preprocessing:/opt/airflow/kedro_preprocessing
      - ./app:/opt/airflow/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mongo_data:
  postgres_data:
  airflow_logs:
  airflow_plugins:
