[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ecotraffic-kedro"
version = "0.1.0"
description = "Kedro preprocessing for EcoTraffic"
requires-python = ">=3.9,<3.12"

[tool.kedro]
package_name = "ecotraffic_kedro"
project_name = "EcoTraffic Kedro"
kedro_init_version = "1.1.1"
source_dir = "src"
[tool.kedro_telemetry]
project_id = "95ceda4325ea447eb81423aac6141fc1"
